name: Test Pipeline

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
    
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use latest stable version
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Tests
        run: npm test
