name: Test Pipeline

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        run: echo "Check Out Code"
    
      - name: Set Up Node.js
        run: echo "Set Up Node.js"
          
      - name: Install Dependencies
        run: echo "Install Dependencies"
        
      - name: Run Tests
        run: echo "Run Tests"
